### ISSUE TITLE
[BUG] Android issue on language change. 

### ISSUE THREAD

**Issue by valdio** [Usercentrics/react-native-sdk#30]
**Describe the bug**
On android when changing the language there are some issues with the content of the modal
Running on:
```
 "react-native": "0.66.4",
"@usercentrics/react-native-sdk": "^2.2.1",
```

- the consent buttons are not visible
- the content of the screen does not change 
- sometimes the android app just crashes 

**To Reproduce**
1. Open the second layer 
2. Change the language to anything

**Expected behavior**
- The content in the new language must be visible.
- The consent buttons must be visible. 

**Screenshots**
Here is an example when changing the language from English-> German
![Screenshot_20220215-164453](https://user-images.githubusercontent.com/12220208/154098326-d3993268-b093-4122-a846-2d756ecd07a7.jpg)
The title changes but not the text under essentials 

**Additional context**

Alternative bug: 
The app crashes when you change the language in android with the following stack trace
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9337)
    at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1727)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3593)
    at android.view.View.requestLayout(View.java:25595)
    at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3593)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.requestLayout(View.java:25595)
    at android.view.View.setFlags(View.java:16252)
    at android.view.View.setVisibility(View.java:11798)
    at com.usercentrics.sdk.ui.components.header.UCHeader.bindLanguage(UCHeader.kt:245)
    at com.usercentrics.sdk.ui.components.header.UCHeader.bind(UCHeader.kt:81)
    at com.usercentrics.sdk.ui.UCSecondLayerView$bindViewModel$1.invoke(UCSecondLayerView.kt:49)
    at com.usercentrics.sdk.ui.UCSecondLayerView$bindViewModel$1.invoke(UCSecondLayerView.kt:48)
    at com.usercentrics.sdk.ui.secondLayer.UCSecondLayerViewModelImpl$onSelectLanguage$1.invoke(UCSecondLayerViewModel.kt:94)
    at com.usercentrics.sdk.ui.secondLayer.UCSecondLayerViewModelImpl$onSelectLanguage$1.invoke(UCSecondLayerViewModel.kt:89)
    at com.usercentrics.sdk.UsercentricsView$invokeChangeLanguage$1.invoke(UsercentricsView.kt:62)
    at com.usercentrics.sdk.UsercentricsView$invokeChangeLanguage$1.invoke(UsercentricsView.kt:54)
    at com.usercentrics.sdk.UsercentricsSDKImpl$changeLanguage$1.invoke(UsercentricsSDKImpl.kt:263)
    at com.usercentrics.sdk.UsercentricsSDKImpl$changeLanguage$1.invoke(UsercentricsSDKImpl.kt:232)
    at com.usercentrics.sdk.services.settings.SettingsLegacy$initSettings$1.invoke(SettingsLegacy.kt:102)
    at com.usercentrics.sdk.services.settings.SettingsLegacy$initSettings$1.invoke(SettingsLegacy.kt:95)
    at com.usercentrics.sdk.v2.settings.facade.SettingsFacade$loadSettings$2.invokeSuspend(SettingsFacade.kt:52)
    at com.usercentrics.sdk.v2.settings.facade.SettingsFacade$loadSettings$2.invoke
    at com.usercentrics.sdk.v2.settings.facade.SettingsFacade$loadSettings$2.invoke
    at com.usercentrics.sdk.v2.async.dispatcher.DispatcherCallback$invokeSuccessBlock$1.invokeSuspend(DispatcherCallback.kt:65)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:233)
    at android.app.ActivityThread.main(ActivityThread.java:8030)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by uc-pedro** [comment]
Hello @valdio, thanks for opening this issue, we will release a hotfix today.
